version: '3.5'
services:
  webapp:
    image: adrianojsa/opendcim:21.01
    build: .
    env_file: .env
    environment:
      DBHOST: db
      DCIM_DB_SCHEMA: ${MYSQL_USER}
      DCIM_DB_USER: ${MYSQL_USER}
      DCIM_DB_PASSWD: ${MYSQL_PASSWORD}
    volumes:
      - ./data:/data
      - ./certs:/certs:ro
    networks:
      - database_net
      - outside
    ports:
      - ${DCIM_HTTP_PORT}:80
      - ${DCIM_HTTPS_PORT}:443
    links:
      - db:db

  db:
    image: mariadb:10.2.14
    command: --sql-mode=NO_ENGINE_SUBSTITUTION
    env_file: .env
    volumes:
     - dcim_db:/var/lib/mysql
    networks:
     - database_net
    restart: always
    
networks:
  database_net:
    driver: bridge
    internal: true
  outside:
    driver: bridge
volumes:
  dcim_db:
    driver: local
